apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: keycloak
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev", "--http-host=0.0.0.0"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_MIGRATION_STRATEGY
              value: "IGNORE"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
              value: "false"
            - name: QUARKUS_TRANSACTION_MANAGER_RECOVERY_FACTORY
              value: "com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule"
            - name: KC_DB
              value: "dev-file"
            - name: KC_DB_URL
              value: "jdbc:h2:file:/opt/keycloak/data/h2/keycloakdb;AUTO_SERVER=TRUE"
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
            requests:
              memory: "1024Mi"
              cpu: "500m"
          volumeMounts:
            - name: keycloak-config
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-config
          persistentVolumeClaim:
            claimName: keycloak-config-pvc