apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.2
          args:
            - "start-dev"
            - "--http-host=0.0.0.0"
            - "--hostname-strict=false"
            - "--import-realm"
            - "--http-enabled=true"
            - "--hostname=voice-chat.pl"
          env:
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HOSTNAME_URL
              value: "https://voice-chat.pl"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres:5432/keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "password"
            - name: KC_BOOTSTRAP_KEYCLOAK_ADMIN
              value: "admin"
            - name: KC_BOOTSTRAP_KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: realm-import
          configMap:
            name: keycloak-realm
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-config-pvc