apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  backend_id: YmFja2VuZA==
  backend_realm: dm9pY2UtY2hhdA==
  backend_secret: SkZnTVhtNkFmRHZJYXZBQmJwbzRLbktvejVFaXJqems=
