# version: "3.8"

services:
  spa:
    container_name: spa-client
    build:
      context: ./client/spa
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_KEYCLOAK_URL: ${NEXT_PUBLIC_KEYCLOAK_URL}
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - voice-service
    networks:
      - app-network
    volumes:
      - ./client/spa:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_KEYCLOAK_URL=${NEXT_PUBLIC_KEYCLOAK_URL}
      - NEXT_PUBLIC_USER_URL=${NEXT_PUBLIC_USER_URL}
      - NEXT_PUBLIC_VOICE_URL=${NEXT_PUBLIC_VOICE_URL}
      - NEXT_PUBLIC_CLIENT_ID=${NEXT_PUBLIC_CLIENT_ID}
      - NEXT_PUBLIC_REALM=${REALM}

  ssr:
    container_name: ssr-client
    build:
      context: ./client/ssr
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - user-service
    networks:
      - app-network
    volumes:
      - ./client/ssr:/app
      - /app/node_modules
    environment:
      - USER_URL=${SSR_USER_URL}
      - KEYCLOAK_URL=${SSR_KEYCLOAK_URL}
      - IP=${IP}

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mongo
      - keycloak
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - VOICE_URL=${VOICE_URL}
      - SPA_URL=${SPA_URL}
      - BACKEND_ID=/run/secrets/backend_id
      - BACKEND_REALM=/run/secrets/backend_realm
      - BACKEND_SECRET=/run/secrets/backend_secret
      - BACKEND_USERNAME=/run/secrets/backend_username
      - BACKEND_PASSWORD=/run/secrets/backend_password
    secrets:
      - backend_realm
      - backend_id
      - backend_secret
      - backend_username
      - backend_password
    networks:
      - app-network
    volumes:
      - ./user-service:/app
      - /app/node_modules

  voice-service:
    build: ./voice-service
    container_name: voice-service
    depends_on:
      - user-service
    ports:
      - "8002:8002"
    environment:
      - USER_URL=${USER_URL}
      - SPA_URL=${SPA_URL}
    networks:
      - app-network
    volumes:
      - ./voice-service:/app
      - /app/node_modules
  
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
      - ./mongo-dump:/dump
    command: >
      bash -c "
        mongorestore --drop /dump/voice-chat &&
        mongod --bind_ip_all
      "
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./keycloak-export/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  keycloak_data:
    driver: local
  mongo-data:
    driver: local

secrets:
  backend_realm:
    file: ./secrets/backend_realm
  backend_id:
    file: ./secrets/backend_id
  backend_secret:
    file: ./secrets/backend_secret
  backend_username:
    file: ./secrets/backend_username
  backend_password:
    file: ./secrets/backend_password