version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - voice-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mongo
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    networks:
      - app-network

  voice-service:
    build: ./voice-service
    container_name: voice-service
    ports:
      - "8002:8002"
    networks:
      - app-network
    
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8003"
    networks:
      - app-network
  
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:

# docker-compose up --build