version: "3.8"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - voice-service
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8001:8001"
    networks:
      - app-network

  voice-service:
    build: ./voice-service
    container_name: voice-service
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

