version: "3.8"

services:
  spa:
    build:
      context: ./client/spa
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - voice-service
    networks:
      - app-network
    volumes:
      - ./client/spa:/app


  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - mongo
      - auth-service
      - voice-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/voice-chat
      - KEYCLOAK_URL=http://keycloak:8080
      - VOICE_URL=http://voice-service:8002
      - AUTH_URL=http://auth-service:8003
    networks:
      - app-network
    volumes:
      - ./user-service:/app

  voice-service:
    build: ./voice-service
    container_name: voice-service
    ports:
      - "8002:8002"
    environment:
      - USER_URL=http://user-service:8001
    networks:
      - app-network
    volumes:
      - ./voice-service:/app
    
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8003"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - SECRET_KEY=hrsbNyY0GOV3W3EUcHnzvZPHqZ1lDKyx
    networks:
      - app-network
    volumes:
      - ./auth-service:/app
  
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet"]
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./realms:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data 
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  keycloak_data:
    driver: local
  mongo-data:
    driver: local

# docker-compose up --build