apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  volumes:
    - name: mongo-dump
      persistentVolumeClaim:
        claimName: mongo-dump-pvc
  containers:
    - name: alpine
      image: alpine
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: mongo-dump
          mountPath: /data