apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssr
  template:
    metadata:
      labels:
        app: ssr
    spec:
      containers:
        - name: ssr-client
          image: jankotanimesigma/voicechat-ssr:v2.0.0
          ports:
            - containerPort: 3001
          env:
            - name: KEYCLOAK_INT_URL
              value: "https://voice-chat.pl"
            - name: KEYCLOAK_PUB_URL
              value: "https://voice-chat.pl"
            - name: USER_URL
              value: "http://user-service:8001"
            - name: SSR_URL
              value: "http://ssr:3001"
          volumeMounts:
            - name: backend-secrets
              mountPath: /app/secrets
              readOnly: true
      volumes:
        - name: backend-secrets
          secret:
            secretName: backend-secrets