apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssr
  template:
    metadata:
      labels:
        app: ssr
    spec:
      containers:
        - name: ssr-client
          image: jankotanimesigma/voicechat-ssr:latest
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 3001
          env:
            - name: KEYCLOAK_URL
              value: "http://keycloak:8080"
            - name: USER_URL
              value: "http://user-service:8001"