apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: jankotanimesigma/voicechat-user-service:latest
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8001
          env:
            - name: SPA_URL
              value: "http://voice-chat.pl:3000/spa"
            - name: VOICE_URL
              value: "http://voice-chat.pl:8002"
            - name: MONGO_URL
              value: "mongodb://mongo:27017/voice-chat"
            - name: KEYCLOAK_URL
              value: "http://voice-chat.pl:8080"