apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-service
  template:
    metadata:
      labels:
        app: voice-service
    spec:
      containers:
        - name: voice-service
          image: jankotanimesigma/voicechat-voice-service:latest
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8002
          env:
            - name: SPA_URL
              value: "https://voice-chat.pl/spa"
            - name: USER_URL
              value: "http://user-service:8001"